info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    spring-cloud-ribbon:
     path: /users/**
     url: http://localhost:8888/users
    zuulserver: /self/**

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
